### ISSUE TITLE
Rewrite 4.3 Version subsets

### ISSUE THREAD

**Issue by brechtvdv** [SEMICeu/LinkedDataEventStreams#1]
First tell "why" you would be making version subsets, because an eventstream in itself is versioned, so why make subsets?

In order to indicate you only keep 1 specific version, e.g., the latest, in your stream
-> 1 specific version of what?
-> 1 specific version for every object

What's the definition of "ldes:amount"? numberOfLatestVersionsPerObject?

How do we tackle other use cases, e.g., what if you only keep the versions between a certain time window and region?

**Comment by pietercolpaert** [comment]
Fixed https://github.com/SEMICeu/LinkedDataEventStreams/commit/dafe3a677d65f448fce2db8a7fe7032fc8ed572a
