### ISSUE TITLE
Consider forbidding indefenite caching of root nodes

### ISSUE THREAD

**Issue by hdelva** [SEMICeu/LinkedDataEventStreams#13]
A client that is already synchronized to an event stream may be disappointed if the data publisher decides to deprecate the fragmentation it's subscribed to, because it may just look like the event stream is no longer updated. 

If root nodes can be cached, clients may never discover the new APIs at all. So should the specification forbid setting root nodes as immutable?

**Comment by pietercolpaert** [comment]
If you want to indicate to client that you’re never going to change your fragmentation from that view, that you should be able to set cache immutable on that view. I don’t see any reason to add something in the specification?

**Comment by pietercolpaert** [comment]
Closing this issue: this should not be in the spec.

**Comment by tuukka** [comment]
Perhaps it would still be valuable to mention this as a note? "Note that if you declare the root immutable, you effectively promise the data consumers that you will never change the fragmentation."
