### ISSUE TITLE
Shape Trees specification link is broken

### ISSUE THREAD

**Issue by KasperZutterman** [SEMICeu/LinkedDataEventStreams#20]
https://shapetrees.github.io/specification/spec possible moved to https://shapetrees.org/TR/specification/

https://github.com/SEMICeu/LinkedDataEventStreams/blob/d2d910bc6b92597dc61361695f581ebaccc18d83/eventstreams.bs#L18

**Comment by pietercolpaert** [comment]
Now also the shapetrees.org domain name is down, but otherwise this link is the official one now which has been updated in the spec.
