### ISSUE TITLE
Add versioning metadata to the Collection

### ISSUE THREAD

**Issue by hdelva** [SEMICeu/LinkedDataEventStreams#21]
Publishes a dataset often entails adding some additional statements (e.g., dct:isVersionOf), but this data then becomes indistinguishable from the original data elements. This can be an issue for operations such as version materializes, which should yield the current version of each concept, as it would appear without this LDES-specific metadata. 

The specification currently describes how to add a version key to a retention policy, but this cannot be used for collections without a retention policy. Furthermore, the version key only specifies which predicate is used to link the version URI to the concept URI, but there's often another predicate that is used to assign a timestamp to this version. This timestamp metadata would also be useful for other issues, such as #16. 

I would propose to move the versioning metadata (the version key and timestamp predicate) to the Collection description, and possibly make it mandatory. Perhaps it can become part of the shape description.

**Comment by pietercolpaert** [comment]
I agree with the suggestion to define this on top of the LDES entity. I think it should be a best practice to define it, but it should not be a requirement though. When defining it, you get a lot of benefits, but functionally everything could keep working without it being described.

## Other use cases

This information would be needed to understand:
 1. how an automatic version materialization could work (related: https://github.com/TREEcg/event-stream-client/issues/13)
 2. how a version-based retention policy would know what the “last” version is (related: #16)
 3. upon what property the members in 1 page need to be ordered to understand how the collection grows, and thus also what member in the page can be automatically discarded when processing such a page again (this is a use case currently hard-coded in the Event Stream client: https://github.com/TREEcg/event-stream-client/blob/31444acb768639745d219b286e050e002f7f38d1/packages/actor-init-ldes-client/lib/EventStream.ts#L209)

## Suggestion

```turtle
ex:ES1 a ldes:EventStream ;
            tree:shape <...> ;
            ldes:versionKey dcterms:isVersionOf ;
            ldes:versionValue dcterms:created .
```

 * `ldes:versionKey` is a property path (Shacl) to the property that will indicate a URI of the non-versioned object
 * `ldes:versionValue` is a property path (Shacl) to the property that can be compared (semver, integer, timestamp) and ordered.

Effects:
 1. An official version materialization can be defined only if the original LDES defines versionKey and versionValue.
 2. A version-based retention policy can be defined based on the original collection’s data, but can also be overwritten in the policy itself. The policy itself can also have the property `ldes:compoundVersionKey` which is an `rdf:List` of version keys indicating that they must be combined. This is particularly useful in e.g. the use case of sensor data to indicate the last 5 sensor observations of a sensor’s observed property (`ldes:compoundVersionKey ( ( sosa:observedProperty ) ( sosa:madeBySensor ) ) .`). 

Possible limitation regarding naming:

What if you don’t have the notion of versionKey, but only a timestamp of new object? Such as with Linked Data Notifications for example. Is the term versionValue poorly chosen then?

**Comment by pietercolpaert** [comment]
Useful remark:

There’s a difference between a sequence number/timestamp for the entire LDES, and a version literal for just comparing among the versions of the same versionOf object. The former would indicate that you should process the entire event stream in order to come to a consistent version materialization, and that certain
