### ISSUE TITLE
Domain of ldes:retentionPolicy does not exist in TREE vocabulary

### ISSUE THREAD

**Issue by julianrojas87** [SEMICeu/LinkedDataEventStreams#23]
The `ldes:retentionPolicy` property is defined as:
```turtle
ldes:retentionPolicy a rdf:Property ;
   rdfs:label "has retention policy"@en;
   rdfs:comment "Links to a retention policy."@en ;
   rdfs:domain tree:View ;
   rdfs:range ldes:RetentionPolicy .
```
But there is no class `tree:View` defined in the [TREE vocabulary](https://github.com/TREEcg/specification/blob/master/tree.ttl). Given that this is a LDES specific property, shouldn't its domain be `ldes:EventStream` instead?

**Comment by pietercolpaert** [comment]
Yes, certainly. We’ll introduce a tree:View as an extra class that gives a URI to the specific view on top of this LDES.

For backwards compatibility we’ll need to make sure that the basic use of this is double typing it with a tree:Node, and maybe even a tree:EntryNode or tree:RootNode

**Comment by pietercolpaert** [comment]
Was fixed now through tree:ViewDescription
