### ISSUE TITLE
Add Additional Hyperlinks to README.md

### ISSUE THREAD

**Issue by Krieke** [SEMICeu/LinkedDataEventStreams#26]
### Section: https://github.com/SEMICeu/LinkedDataEventStreams#the-linked-data-event-streams-specification:
- First alinea: create a hyperlink on `RDF` to https://www.w3.org/RDF/
- Fourth alinea: create hyperlinks on `Activity Streams` to https://www.w3.org/TR/activitystreams-core/, on `DCAT-AP` to https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe, on `LDP` to https://www.w3.org/TR/ldp/ or `Shape Trees` to https://shapetrees.org/.

### Section: https://github.com/SEMICeu/LinkedDataEventStreams#build-the-spec : 
- create a hyperlink on `bikeshed` to the bikeshed documentation GitHub pages link https://tabatkins.github.io/bikeshed/ 

### Section: https://github.com/SEMICeu/LinkedDataEventStreams#acknowledgements
- create a hyperlink on `SEMIC` to https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic

**Comment by pietercolpaert** [comment]
Fixed in https://github.com/SEMICeu/LinkedDataEventStreams/commit/363942d49428b101f433f9371de4bdbc920cea0a
