### ISSUE TITLE
Alignment for LDES as time-series

### ISSUE THREAD

**Issue by woutslabbinck** [SEMICeu/LinkedDataEventStreams#28]
Issue to start a discussion on how to deal with time-series with LDES.

Pointers:

- [LDES in LDP](https://woutslabbinck.github.io/LDESinLDP/): deals with a time-fragmented LDES (stored on an LDP) using GTE relations.

**Comment by pietercolpaert** [comment]
I think Linked Data Event Streams with Time Series snippets will need to be a separate specification at first. Will consider this out of scope of the SEMIC specification for now.
