### ISSUE TITLE
broken link to Open Web Foundation Agreement Version 1.0

### ISSUE THREAD

**Issue by marc-portier** [SEMICeu/LinkedDataEventStreams#30]
the current link is to http://www.openwebfoundation.org/legal/the-owf-1-0-agreements/owfa-1-0 which yields 404

probably needs to be updated to https://www.openwebfoundation.org/the-agreements/the-owf-1-0-agreements-granted-claims/owfa-1-0

**Comment by pietercolpaert** [comment]
Interesting! Seems this is a problem in bikeshed where I’ve opened the issue: https://github.com/speced/bikeshed/issues/2509
