### ISSUE TITLE
https://tree.linkeddatafragments.org/linked-data-event-streams/ cannot be reached

### ISSUE THREAD

**Issue by xdxxxdx** [SEMICeu/LinkedDataEventStreams#52]
Hello @pietercolpaert,

[https://tree.linkeddatafragments.org/linked-data-event-streams/](https://tree.linkeddatafragments.org/linked-data-event-streams/ )
cannot be reached anymore
![image](https://github.com/SEMICeu/LinkedDataEventStreams/assets/15314807/c8bcdc3c-3563-4b19-9e2c-4f54107b2607)
![image](https://github.com/SEMICeu/LinkedDataEventStreams/assets/15314807/c0e33de9-d46c-41a2-94a9-57a7a21ca9ef)
Thanks

**Comment by pietercolpaert** [comment]
There has been an outage on our lab’s servers tonight. The servers are up and running but we’re waiting for connections to restore! This can still take a couple of hours.
